import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/navbar";
import { PokemonProvider } from "@/context/pokemonProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <PokemonProvider>
<div className="  bg-transparent opacity-85  relative min-h-screen bg-fixed bg-cover bg-center"
     style={{ backgroundImage: "url('/image/bg-dex.jpg')" }}>
  
       <Navbar />
        {children}
</div>
      </PokemonProvider>
      </body>
    </html>
  );
}
