import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { PokemonProvider } from "@/context/pokemonProvider";
import { ClerkProvider } from "@clerk/nextjs";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <PokemonProvider>
            {/* <div className="relative w-screen h-screen ">
              {/* Blurred background layer */}
            {/* <div
                className="absolute inset-0 bg-fixed bg-cover bg-center filter blur-xs"
                style={{ backgroundImage: "url('/image/bg-dex.jpg')" }}
              ></div>  */}

            {/* Content layer */}
            {/* <div className="relative z-10 w-full "> */}
            <div className="relative h-screen overflow-hidden flex flex-col items-center justify-center">
              {/* Background layer (blur only here) */}
              <div
                className="absolute inset-0 -z-10 bg-cover bg-center blur-xs"
                style={{ backgroundImage: "url('/image/bg-dex.jpg')" }}
              />

              {/* Foreground layer (not blurred) */}
              <Navbar />
              {children}
            </div>

            {/* </div>
            </div>
             */}
          </PokemonProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
